<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container71sAFVT\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container71sAFVT/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container71sAFVT.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container71sAFVT\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container71sAFVT\App_KernelProdContainer([
    'container.build_hash' => '71sAFVT',
    'container.build_id' => '3b34eba8',
    'container.build_time' => 1631384207,
], __DIR__.\DIRECTORY_SEPARATOR.'Container71sAFVT');
