#Ponemos un alias para hacer referencia
FROM node:14.17.4-alpine3.14 as build
#Creamos un directorio y nos movemos a él
WORKDIR /Elrincondelaprogramacion
#Copiamos al directorio anterior
COPY App/Elrincondelaprogramacion ./
#Por si se copió node_modules lo borramos, instalamos las dependencias y pasamos a producción
RUN rm -r ./node_modules && npm i && npm run build --prod

FROM nginx:stable-alpine
#Copiamos lo anterior 
COPY --from=build /Elrincondelaprogramacion/dist/Elrincondelaprogramacion /var/www/Proyecto