#Ponemos un alias para hacer referencia
FROM node:14.17.4-alpine3.14 as build
#Creamos un directorio y nos movemos a él
WORKDIR /Elrincondelaprogramacion
#Copiamos al directorio anterior
COPY App/Elrincondelaprogramacion ./
#Instalamos las dependencias y pasamos a producción
RUN npm i && npm run build --prod

FROM nginx:stable-alpine
#Copiamos lo anterior 
COPY --from=build /Elrincondelaprogramacion/dist/Elrincondelaprogramacion /var/www/Proyecto
COPY Nginx/virtual-hosts/elrincondelaprogramacion.com /etc/nginx/conf.d/default.conf
COPY Nginx/domains/frontend /etc/hosts
COPY Nginx/certificates /etc/ssl/certs/