FROM php:8.0-fpm-alpine
#Actualizamos los paquetes de apk, instalamos bash y las extensiones de PHP
RUN apk --no-cache update && apk --no-cache add bash && docker-php-ext-install pdo pdo_mysql
#Creamos este directorio y nos movemos a él
WORKDIR /var/www/Proyecto
COPY App/Elrincondelaprogramacion-API ./
RUN chmod 777 ./var/log