lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 604800


    token_extractors:
        #Comprueba el token mediante una cookie
        cookie:
            enabled: true
            name: token
            
    set_cookies:   
        token:
            #Por defecto la que ya configuramos
            lifetime: null
            samesite: lax
            path: /
            #Por defecto nuestro dominio
            domain: null 
            #HTTPS
            secure: false
            #Irá por la cabecera
            httpOnly: true   