lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 604800


    token_extractors:
        #Comprueba el token mediante una cookie
        cookie:
            enabled: true
            name: token
            
    set_cookies:   
        token:
            #Por defecto la que ya configuramos
            lifetime: null
            #Al poner none la cookie s칩lo ser치 establecida en el frontend si la conexi칩n es segura
            samesite: none
            path: /
            #Por defecto nuestro dominio
            domain: null 
            #HTTPS
            secure: true
            #Ir치 por la cabecera
            httpOnly: true   