version: '3'

networks:
    nginx-php8-mysql:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php8-service
            - mysql-service
        networks:
            - nginx-php8-mysql

    # php
    php8-service:
        build:
            context: .
            dockerfile: ./Php/dockerfile
        container_name: php8-container
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project
        networks:
            - nginx-php8-mysql

    # mysql
    mysql-service:
        image: mysql
        container_name: mysql-container
        ports:
            - "4306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: 
            MYSQL_PASSWORD:
        networks:
            - nginx-php8-mysql
