<?php

namespace ContainerNktPlnJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E439WMtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e439WMt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e439WMt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'filesystem' => ['services', '.container.private.filesystem', 'get_Container_Private_FilesystemService', true],
        ], [
            'filesystem' => '?',
        ]);
    }
}
