<?php

namespace ContainerNktPlnJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLexikJwtAuthentication_CookieProvider_TokenService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'lexik_jwt_authentication.cookie_provider.token' shared service.
     *
     * @return \Lexik\Bundle\JWTAuthenticationBundle\Security\Http\Cookie\JWTCookieProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/lexik/jwt-authentication-bundle/Security/Http/Cookie/JWTCookieProvider.php';

        return $container->privates['lexik_jwt_authentication.cookie_provider.token'] = new \Lexik\Bundle\JWTAuthenticationBundle\Security\Http\Cookie\JWTCookieProvider('token', 31536000, 'none', '/', NULL, true, true, []);
    }
}
