<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNktPlnJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNktPlnJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNktPlnJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNktPlnJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNktPlnJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'NktPlnJ',
    'container.build_id' => 'dbbf45fc',
    'container.build_time' => 1631383355,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNktPlnJ');
