FROM php:8.0-fpm-alpine
RUN apt-get update && apt-get install -y zlib1g-dev g++ git libicu-dev zip libzip-dev zip \
    && docker-php-ext-install intl opcache pdo pdo_mysql \
    && pecl install apcu \
    && docker-php-ext-enable apcu \
    && docker-php-ext-configure zip \
    && docker-php-ext-install zip
#Descargamos Composer y copiamos su directorio en nuestro directorio
COPY --from=composer /usr/bin/composer /usr/bin/composer
WORKDIR /var/www/Proyecto
COPY App/Elrincondelaprogramacion-API/ ./
#Por si se copió vendor lo borramos e instalamos las dependencias
RUN rm -r ./vendor && composer install