FROM php:8.0-fpm-alpine
RUN apk --no-cache update && apk --no-cache add bash && docker-php-ext-install pdo pdo_mysql
#Descargamos Composer y copiamos su directorio en nuestro directorio
COPY --from=composer /usr/bin/composer /usr/bin/composer
WORKDIR /var/www/Proyecto
COPY App/Elrincondelaprogramacion-API/ ./
#Por si se copió vendor lo borramos e instalamos las dependencias
RUN rm -r ./vendor && composer install