#User
register:
    path: /api/register
    controller: App\Controller\UserController::register
    methods: POST

login:
    path: /api/login
    methods: POST

updateUser:
    path: /api/users/{id}/update
    controller: App\Controller\UserController::update
    methods: PUT

uploadProfileImage:
    path: /api/profile-image/upload
    controller: App\Controller\UserController::uploadProfileImage
    methods: POST

getProfileImage:
    path: /api/profile-image/{image-name}
    controller: App\Controller\UserController::getProfileImage
    methods: GET

getUser:
    path: /api/users/{id}
    controller: App\Controller\UserController::getUserDetail
    methods: GET

banUser:
    path: /api/users/{id}/ban
    controller: App\Controller\UserController::ban
    methods: PUT

#Category
createCategory:
    path: /api/category/create
    controller: App\Controller\CategoryController::create
    methods: POST

updateCategory:
    path: api/categories/{id}/update
    controller: App\Controller\CategoryController::update
    methods: PUT

getCategories:
    path: /api/categories
    controller: App\Controller\CategoryController::getCategories
    methods: GET

getCategory:
    path: /api/categories/{id}
    controller: App\Controller\CategoryController::getCategory
    methods: GET

deleteCategory:
    path: api/categories/{id}/delete
    controller: App\Controller\CategoryController::delete
    methods: DELETE
  
#Post
createPost:
    path: /api/post/create
    controller: App\Controller\PostController::create
    methods: POST

updatePost:
    path: /api/posts/{id}/update
    controller: App\Controller\PostController::update
    methods: PUT

getPosts:
    path: /api/posts
    controller: App\Controller\PostController::getPosts
    methods: GET

getPost:
    path: /api/posts/{id}
    controller: App\Controller\PostController::getPost
    methods: GET

deletePost:
    path: /api/posts/{id}/delete
    controller: App\Controller\PostController::delete
    methods: DELETE

#Comment
createComment:
    path: /api/comment/create
    controller: App\Controller\CommentController::create
    methods: POST

deleteComment:
    path: /api/comments/{id}/delete
    controller: App\Controller\CommentController::delete
    methods: DELETE
