#Users
login:
    path: /api/login
    methods: POST
    
register:
    path: /api/register
    controller: App\Controller\UserController::register
    methods: POST

updateUser:
    path: /api/users/{id}/update
    controller: App\Controller\UserController::update
    methods: PUT

uploadProfileImage:
    path: /api/profile-image/upload
    controller: App\Controller\UserController::uploadProfileImage
    methods: POST

getProfileImage:
    path: /api/profile-image/{image-name}
    controller: App\Controller\UserController::getProfileImage
    methods: GET

getUser:
    path: /api/users/{id}
    controller: App\Controller\UserController::getUserDetail
    methods: GET

#Post
create:
    path: /api/post/create
    controller: App\Controller\PostController::create
    methods: POST