#User
register:
    path: /register
    controller: App\Controller\UserController::register
    methods: POST

login:
    path: /login
    methods: POST

updateUser:
    path: /users/{id}/update
    controller: App\Controller\UserController::update
    methods: PUT

uploadProfileImage:
    path: /profile-image/upload
    controller: App\Controller\UserController::uploadProfileImage
    methods: POST

getProfileImage:
    path: /profile-images/{image-name}
    controller: App\Controller\UserController::getProfileImage
    methods: GET

getUser:
    path: /users/{id}
    controller: App\Controller\UserController::getUserDetail
    methods: GET

banUser:
    path: /users/{id}/ban
    controller: App\Controller\UserController::ban
    methods: PUT

logout:
    path: /logout
    controller: App\Controller\UserController::logout
    methods: DELETE

#Category
createCategory:
    path: /category/create
    controller: App\Controller\CategoryController::create
    methods: POST

updateCategory:
    path: /categories/{id}/update
    controller: App\Controller\CategoryController::update
    methods: PUT

getCategories:
    path: /categories
    controller: App\Controller\CategoryController::getCategories
    methods: GET

getCategory:
    path: /categories/{id}
    controller: App\Controller\CategoryController::getCategory
    methods: GET

deleteCategory:
    path: /categories/{id}/delete
    controller: App\Controller\CategoryController::delete
    methods: DELETE
  
#Post
createPost:
    path: /post/create
    controller: App\Controller\PostController::create
    methods: POST

updatePost:
    path: /posts/{id}/update
    controller: App\Controller\PostController::update
    methods: PUT

uploadImage:
    path: /post-image/upload
    controller: App\Controller\PostController::uploadImage
    methods: POST

getImage:
    path: /posts-images/{imageName}
    controller: App\Controller\PostController::getImage
    methods: GET

getPosts:
    path: /posts
    controller: App\Controller\PostController::getPosts
    methods: GET

getUserPosts:
    path: /posts/users/{userId}
    controller: App\Controller\PostController::getUserPosts
    methods: GET

getPostsByCategory:
    path: /posts/categories/{categoryId}
    controller: App\Controller\PostController::getPostsByCategory
    methods: GET

getPostDetail:
    path: /posts/{id}
    controller: App\Controller\PostController::getPostDetail
    methods: GET

indequatePost:
    path: /posts/{id}/inadequate
    controller: App\Controller\PostController::inadequate
    methods: PUT

#Comment
createComment:
    path: /{postId}/comment/create
    controller: App\Controller\CommentController::create
    methods: POST

indequateComment:
    path: /comments/{id}/inadequate
    controller: App\Controller\CommentController::inadequate
    methods: PUT
